version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=url_shortener
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=url_shortener
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql-data: